server:
  port: 8080
spring:
  application:
    name: USER-SERVICE
  # Mysql 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/filming?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    # DB username / password
    username: root
    password: test1357
  jpa:
    show-sql: true
    hibernate:
      # create  :  기존 테이블을 삭제하고 새로 생성 [ DROP + CREATE ]
      # create-drop  :  CREATE 속성에 추가로 어플리케이션을 종료할 때 생성한 DDL을 제거  [ DROP + CREATE + DROP ]
      # update  :  DB 테이블과 엔티티 매핑 정보를 비교해서 변경 사항만 수정 [ 테이블이 없을 경우 CREATE ]
      # validate  :  DB 테이블과 엔티티 매핑정보를 비교해서 차이가 있으면 경고를 남기고 어플리케이션을 실행하지 않음
      # none  :  자동 생성 기능을 사용하지 않음
      ddl-auto: update
    # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    eureka-server-port: 8761
  instance:
    appname: USER-SERVICE

